<br><br>
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr><td align="center">
<?
/*
Your getting this sweet booking application for free under the gpl, all I ask is that you leave my copyright
notice and link to my page intact.  The link drives traffic to my site ensuring that this app will
continue to be developed.  Plus it gives me fame!! and tons of women.
*/
print font("Page","foot");
?>
HLb 0.99-beta2 is Powered by <a href="http://sourceforge.net/projects/phpstep/" target="phpstep">PHPStep</a>
<br>(c)2000-2003 <a href="http://www.playway.net" target="playway">Playway.net LLC</a></font>
</td></tr></table>
<br><br>
